version: "2"
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    command: "lein run"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
